"""Description for Thread

Revision ID: c72d9df38aa8
Revises: bc58167d9237
Create Date: 2020-09-27 23:15:34.727349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72d9df38aa8'
down_revision = 'bc58167d9237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'description')
    # ### end Alembic commands ###
